54 - introduced react to confidence slider
adaptlearning/adapt-contrib-confidenceSlider pull request #55
Opened 2022-02-03 12:11 UTC by eleanor-heath

2022-02-03 12:15 UTC, ethan-lp approved these changes

2022-02-03 15:35 UTC, cahirodoherty-learningpool approved these changes
👀

2022-02-04 09:41 UTC, lc-alexanderbenesch approved these changes
👍

2022-02-14 11:10 UTC, joe-allen-89 approved these changes
👍

2022-02-21 11:39 UTC, oliverfoster requested changes

2022-02-21 11:39 UTC, oliverfoster commented on templates/confidenceSlider.jsx
> +  const shouldShowMarking = isInteractive() && _canShowMarking;
https://github.com/adaptlearning/adapt-contrib-core/blob/759b768057ef3d88d83328121fdec25f1a96bb93/js/models/questionModel.js#L368-L374

You should be able to use `_shouldShowMarking` directly from the model now.

2022-02-21 12:09 UTC, oliverfoster commented
@eleanor-heath Could you see if this has an easy fix whilst you're here? https://github.com/adaptlearning/adapt_framework/issues/3238

2022-02-21 14:51 UTC, eleanor-heath commented
> @eleanor-heath Could you see if this has an easy fix whilst you're here? [adaptlearning/adapt_framework#3238](https://github.com/adaptlearning/adapt_framework/issues/3238)
will do

2022-02-23 10:02 UTC, oliverfoster commented on js/confidenceSliderView.js
> +    this.$('.component__body-inner').html(linkedModel.get('body'));
```suggestion
    this.$('.component__body-inner').html(this.model.get('body'));
```
This should probably be the body from the model for this instance and not the linked instance.

2022-02-23 12:28 UTC, merged