Fix: display feedback
adaptlearning/adapt-contrib-confidenceSlider pull request #76
Opened 2022-12-15 12:59 UTC by danielghost

Fixes #75

### Fix
* Feedback should now be displayed as required
* Added `title` and `altTitle` to schemas and readme. Amended functionality to match other questions as per https://github.com/adaptlearning/adapt-contrib-core/pull/223 - no longer uses component titles if empty.

2022-12-15 17:00 UTC, cahirodoherty-learningpool approved these changes
👀

2023-01-03 17:09 UTC, chris-steele approved these changes

2023-01-04 11:26 UTC, joe-allen-89 approved these changes

2023-01-04 11:32 UTC, joe-allen-89 requested changes
We'll need to add title/altTitle to example.json

2023-01-09 11:34 UTC, oliverfoster commented
@danielghost see @joe-allen-89 comment about example.json

2023-01-09 14:49 UTC, merged